"""Update users table

Revision ID: 7595b994ba8d
Revises: 2dfe35bb4c09
Create Date: 2023-09-19 14:04:08.525177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7595b994ba8d'
down_revision = '2dfe35bb4c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'owner_id')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'role')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'description')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'created_at')
    op.add_column('item', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
